name: GOPRO_S3
model_type: S3_Model
scale: 1
num_gpu: 1
manual_seed: 0

datasets:
  train:
    name: GOPRO
    type: GOPRODataset
    dataroot_gt: dataset/GoPro/train/sharp
    dataroot_lq: dataset/GoPro/train/blur
    meta_info_file_train: basicsr/data/meta_info/meta_info_GOPRO_GT.txt
    io_backend:
      type: disk
    num_frame: 15
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 200
    prefetch_mode: ~
    phase: train
    scale: 1

  val:
    name: GOPRO
    type: VideoRecurrentSplitClipsTestDataset
    dataroot_gt: dataset/GoPro/test/sharp
    dataroot_lq: dataset/GoPro/test/blur
    cache_data: false
    io_backend:
      type: disk

    num_frame: 30
    num_overlap: 0
    phase: val
    scale: 1

network_g:
  type: S3_arch
  num_feat: 64
  propagation_blocks: 30
  num_blocks: [7,2]
  heads: [4,8]
  use_cross_attention: false
  cross_attention_heads: 2
  bias: false
  n_denoise_res: 1
  linear_start: 0.1
  linear_end: 0.99
  timesteps: 4

path:
  pretrain_network_g: ~
  pretrain_network_S2: experiments/GOPRO_S1_final/models/net_g_300000.pth
  strict_load_g: True
  resume_state: ~


train:
  optim_g:
    type: AdamW
    lr: !!float 8e-5
    weight_decay: !!float 4e-5
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
  
  fft_opt:
    type: FFT
    loss_weight: 0.1
    reduction: mean


val:
  val_freq: 5000
  save_img: True
  use_patch: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
    ssim:
      type: calculate_ssim
      crop_border: 0


logger:
  print_freq: 1000
  save_checkpoint_freq: 5000
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
